- name: run container with k8s
  become: true
  ansible.builtin.shell: 
    cmd: kubectl create deployment hello-node --image={{ docker_image_name }} && kubectl expose deployment hello-node --type=LoadBalancer --port=8080

